### PR TITLE
DEV: implements with Search instead of TopicQuery

### PR DESCRIPTION
**Pull request by jjaffeux**
Note the syntax is now:

```
[query=foo]
```

And not `[topic query=foo]\n[/topic]` anymore.

### CODE REVIEW

**Comment by jjaffeux** [comment]
Various use cases:

Capture d’écran 2021-11-05 à 17 59 33

**Review by eviltrout — APPROVED** [review]
`query` does sound very generic to me. Having said that I suspect this would be the #1 use for querying things in a post.

**Comment by jjaffeux** [comment]
I could go with search-query if you think that’s better?

**Comment by jjaffeux** [comment]
@eviltrout I went with search-query for now, I think it conveys nicely the purpose

**Comment by eviltrout** [comment]
Great, thank you!

**Pull request merged**
